In [1]:
# 대학입시 합격 예측 딥러닝 실습
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical

In [2]:
# 1. 데이터 불러오기
url = 'university_admission.csv'

df = pd.read_csv(url)
print(df.head())

   ID  Exam_Score  School_Grade  Absent_Days  University_Level  Pass
0   1         324          3.46            9                 2     0
1   2         293          3.95            7                 4     1
2   3         332          2.30            5                 3     1
3   4         376          3.28            3                 1     0
4   5         288          2.67            7                 1     0


In [3]:
# 2. 입력(X)과 타겟(y) 설정
X = df[['Exam_Score', 'School_Grade', 'Absent_Days', 'University_Level']].values
y = df['Pass'].values

In [4]:
# 3. 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#print(X_train[:2], X_test[:2], y_train[:2], y_test[:2])

In [5]:
# 4. 특성 스케일링
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train[:2], X_test[:2], y_train[:2], y_test[:2])

[[-1.73336535 -0.12703566 -0.30183416 -1.83223588]
 [-0.26659536 -1.52726891  0.7389733  -0.14159147]] [[ 1.29928072  0.9890923   0.04510166 -1.83223588]
 [-0.46480752  0.11648317  0.04510166 -1.83223588]] [0 1] [0 0]


In [6]:
# 5. 모델 만들기
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(4,)),
    tf.keras.layers.Dense(16, activation='sigmoid'),
    tf.keras.layers.Dense(280, activation='sigmoid'),
    tf.keras.layers.Dense(2, activation='sigmoid')
])

model.summary()

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 280)            │         4,760 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │           562 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,402 (21.10 KB)

 Trainable params: 5,402 (21.10 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#모델 실행
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [8]:
# 6. 타겟 데이터 one-hot 인코딩
y_train_cat = to_categorical(y_train, num_classes=2)
y_test_cat = to_categorical(y_test, num_classes=2)

In [9]:
# 7. 모델 훈련
model.fit(X_train, y_train_cat, epochs=30, validation_split=0.2)

Epoch 1/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.4914 - loss: 0.8744 - val_accuracy: 0.4500 - val_loss: 0.7428
Epoch 2/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4545 - loss: 0.7212 - val_accuracy: 0.5500 - val_loss: 0.6811
Epoch 3/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5106 - loss: 0.6937 - val_accuracy: 0.5750 - val_loss: 0.6691
Epoch 4/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5562 - loss: 0.6791 - val_accuracy: 0.7875 - val_loss: 0.6627
Epoch 5/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6283 - loss: 0.6623 - val_accuracy: 0.5500 - val_loss: 0.6523
Epoch 6/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6351 - loss: 0.6623 - val_accuracy: 0.8250 - val_loss: 0.6431
Epoch 7/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7741 - loss: 0.6388 - val_accuracy: 0.6500 - val_loss: 0.6287
Epoch 8/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7684 - loss: 0.6245 - val_accuracy: 0.8375 - val_loss

In [10]:
# 8. 모델 평가
loss, accuracy = model.evaluate(X_test, y_test_cat)
print(f"\nTest Accuracy: {accuracy:.4f}")

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8954 - loss: 0.2657 

Test Accuracy: 0.9000


In [11]:
import numpy as np

# 새로운 학생 데이터 입력 받기
exam_score = float(input("수능 점수를 입력하세요: "))        # 예: 310
school_grade = float(input("내신 등급을 입력하세요 (예: 3.1): "))  # 예: 3.1
absent_days = int(input("결석 일수를 입력하세요: "))           # 예: 2
university_level = int(input("지원 대학 등급을 입력하세요 (1~5): "))  # 예: 2

# 입력 데이터를 배열 형태로 묶기
new_student = np.array([[exam_score, school_grade, absent_days, university_level]])

# 데이터 스케일링 (학습할 때 사용한 scaler로 변환)
new_student_scaled = scaler.transform(new_student)

# 예측하기
pred = model.predict(new_student_scaled)

# 결과 해석
predicted_class = np.argmax(pred)

# 출력하기
print("합격 확률:", round(pred[0][1] * 100, 2), "%")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
합격 확률: 61.29 %
